name: CI

on:
  push:
    branches:
      - main # Change this to your default branch if it's different
  pull_request:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Specify your Node.js version here

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build
        working-directory: client
        run: npm run build

      - name: Test
        working-directory: client
        run: npm test
