name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      # Use Node.js version specified in the matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies, build, and test in the 'client' folder
      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build the project
        run: npm run build --if-present
        working-directory: ./client

      - name: Run tests
        run: npm test
        working-directory: ./client
